# Generated by Django 5.2.17 on 2026-08-25 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('renal', 'Renal'), ('leukemia', 'Leucemia')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Concluída'), ('failed', 'Falhou')], max_length=20)),
                ('input_image', models.ImageField(blank=True, upload_to='analyses/%Y/%m/%d/')),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('inference_time_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
