# Generated by Django 5.2.17 on 2026-08-25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeukemiaAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_image",
                    models.ImageField(
                        upload_to="leukemia/analyses/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Concluída"),
                            ("failed", "Falhou"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "predicted_class",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("malignant", "Maligna"),
                        ],
                        max_length=20,
                    ),
                ),
                ("malignant_score", models.FloatField()),
                ("normal_score", models.FloatField()),
                ("decision_threshold", models.FloatField()),
                ("inference_time_ms", models.FloatField()),
                ("original_width", models.PositiveIntegerField()),
                ("original_height", models.PositiveIntegerField()),
                ("experimental", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
